name: Test

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, mac-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        pytest-version: ["9"]
        cython-version: ["3"]
        editable-install: ["true", "false"]

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }} [pytest ${{ matrix.pytest-version }}, cython ${{ matrix.cython-version }}]
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools

        python -m pip install pytest==${{ matrix.pytest-version }}.*
        python -m pip install cython==${{ matrix.cython-version }}.*
        python -m pip install -e .

    - name: Install example-project (editable)
      run: python -m pip install -e tests/example-project
      if: ${{ matrix.editable-install == 'true' }}

    - name: Install example-project (non-editable)
      run: python -m pip install tests/example-project
      if: ${{ matrix.editable-install == 'false' }}

    - name: Test with pytest
      env:
        PY_IGNORE_IMPORTMISMATCH: "1"
      run: pytest -vv tests
