name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: >-
      Test
      ${{ matrix.os }}
      -Py=${{matrix.python-version}}
      -pytest=${{ matrix.pytest-version }}
      -Cy=${{ cython-version }}
      -${{ matrix.editable-install == 'false' && 'non' || '' }}editable
    runs-on: ${{ matrix.os }}
    concurrency:
      group: test-${{ github.event_name == 'push' && github.run_number || github.ref }}-${{ toJSON(matrix) }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        pytest-version: ["9"]
        cython-version: ["3"]
        editable-install: ["true", "false"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install uv/Python
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: "true"

    - name: Install dependencies
      run: uv pip install .[lint]

    - name: Install example-project (editable)
      run: uv pip install -e tests/example-project
      if: ${{ matrix.editable-install == 'true' }}

    - name: Install example-project (non-editable)
      run: uv pip install tests/example-project
      if: ${{ matrix.editable-install == 'false' }}

    - name: Show versions
      run: uv pip freeze

    - name: Run pytest
      env:
        PY_IGNORE_IMPORTMISMATCH: "1"
      run: pytest -vv tests/
